import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  schema: './src/lib/db/schema.ts',
  out: './migrations',
  dialect: 'sqlite',
  // This is a workaround for local development with D1.
  // The sqlite file is generated by wrangler, but the name is a hash.
  // A better solution would be to dynamically find this file.
  dbCredentials: {
    url: '.wrangler/state/v3/d1/miniflare-D1DatabaseObject/6568c2a4ec7f4578b0d5e9e13a3aa695ce2a695347d066f36246209891cac959.sqlite',
  },
});
