name = "rgou-main"
main = "src/worker.ts"
compatibility_date = "2026-07-14"
account_id = "571f130502618993d848f58d27ae288d"

[assets]
directory = "./out/client"
binding = "ASSETS"
run_worker_first = true
not_found_handling = "single-page-application"

[vars]
ENVIRONMENT = "production"
SENTRY_ENVIRONMENT = "production"
SENTRY_PROJECT = "rgou-cloudflare"

[observability]
enabled = true
head_sampling_rate = 1

[[routes]]
pattern = "rgou.tre.systems/*"
zone_name = "tre.systems"

[[routes]]
pattern = "gameofur.org/*"
zone_name = "gameofur.org"

[[routes]]
pattern = "www.gameofur.org/*"
zone_name = "gameofur.org"

[[routes]]
pattern = "gameofur.net/*"
zone_name = "gameofur.net"

[[routes]]
pattern = "www.gameofur.net/*"
zone_name = "gameofur.net"

[[analytics_engine_datasets]]
binding = "APP_USAGE"
dataset = "app_usage"
